### PR TITLE
Implementation of span-query highlighting.

### PR DESCRIPTION
**Pull request by mkrauklis**
Potential Fix for #20 

Supported span-query-types:
span_term
span_multi
span_near
span_or

### CODE REVIEW

**Comment by MrSaints** [comment]
Out of curiosity, what's the status of this PR? 🤔

**Comment by mkrauklis** [comment]
Sorry to have let it languish. We haven't had the bandwidth to fully investigate @nomoa 's suggestion. We're using a fork that uses the implementation in the PR and haven't had any issues.

**Comment by rpedela** [comment]
Does this PR help with ```match_phrase``` with ```slop``` queries too?

**Comment by mkrauklis** [comment]
My inkling is no, unless at some point under the hood those get converted and processed as span_nears after analysis. I would imagine this solution _could_ be expanded upon to support match_phrase + slop.

**Pull request closed without merging**
